### ISSUE TITLE
Level design

### ISSUE THREAD

**Issue by KylarJordgubbar** [KylarJordgubbar/C4#2]
välj vart plattformar ska vara någonstans för att få en bra map

**Comment by lhn18** [comment]
Ville få platform att rotera, men något saknas för funktionen.

``var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    /*backgroundColor: '',*/
    parent: 'C4-master',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var game = new Phaser.Game(config);

var group;

function preload ()
{
    this.load.spritesheet('platform', 'assets/platform.png', { frameWidth: 32, frameHeight: 24 });
}

function create ()
{
    group = this.add.group();

    for (var i = 0; i < 256; i++)
    {
        group.create(Phaser.Math.Between(200, 600), Phaser.Math.Between(100, 500), 'platform', Phaser.Math.Between(0, 4));
    }
}

function update ()
{
    Phaser.Actions.RotateAround(group.getChildren(), { x: 400, y: 300 }, 0.01);
} ``

**Comment by lhn18** [comment]
Skulle ju vara trevligt att kunna hantera funktionerna som i exemplet: https://itnext.io/modular-game-worlds-in-phaser-3-tilemaps-5-matter-physics-platformer-d14d1f614557

**Comment by KylarJordgubbar** [comment]
Inte helt säker på att jag förstår problemet, vi får ta och snacka om det imorgon.

Men om man läser dokumentationen<https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Group.html> för klassen group, som är den du använder I mailet, så ser man att den inte har någon fuktion för att rotera childs. Det kanske går att jobba runt,  men jag skulle tipsa om att läsa på lite i dokumentationen.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
